export const UI_COPY = {
  zh: {
    metaDescription: 'greenthree blog——记录物理、算法与让思想运动起来的代码。',
    nav: { quantum: '量子态', notebook: '文章', topics: '主题', resources: '资源' },
    stateVector: '态矢量 / 布洛赫球',
    interactive: '可交互',
    blochLabel: '交互式布洛赫球。使用指针或方向键旋转态矢量。',
    physicsBlog: '物理系学生博客 / 001',
    hero: { line1: '量子', accent: '前沿', joiner: '与', line3: '算法', line4: '漫游' },
    heroDescription: '记录严谨物理与优雅算法，也记录让思想运动起来的代码。',
    explore: '浏览文章',
    archive: '笔记归档',
    articleUnit: '篇文章',
    emptyArchive: '尚未索引文章。请在 src/content/ 中添加 Markdown 文件。',
    archiveInstruction: '导入 .MD 文件 / 重新构建 / 发布',
    hashRoutes: '固定链接已启用',
    wave: '波函数演化 // WAVE_FUNCTION',
    waveDescription: '观察波包干涉、概率振幅与相位如何在离散晶格中演化。',
    waveLabel: '概率振幅波形',
    amplitudeLabel: '概率振幅',
    topics: '热门主题',
    footer: '页脚',
    social: '社交',
    about: 'greenthree 的网站与实验笔记，从第一性原理开始构建。',
    contact: '联系',
    renderCore: '性能监控',
    representation: '表象',
    renderTelemetry: '渲染遥测',
    openTelemetry: '展开性能监控',
    closeTelemetry: '收起性能监控',
    state: '态',
    closeArticle: '关闭文章',
    closeTopic: '关闭主题',
    endNote: '文章结束',
    returnArchive: '返回归档',
    loadingArticle: '正在载入文章',
    copyCode: '复制代码',
    copied: '已复制',
    copyFailed: '复制失败',
    errorTitle: '渲染状态异常',
    errorDescription: '组件渲染过程中出现异常，请重置后重试。',
    reset: '重置并重新渲染',
    views: '次点击',
    viewsLoading: '正在读取点击数',
    viewsUnavailable: '点击数暂时不可用',
    openMenu: '打开导航',
    closeMenu: '关闭导航',
    languageControl: '切换网站语言',
    query: '检索',
    topicQueued: '该主题来自当前文章索引。打开对应场记，可继续查看相关实验、代码与推导。',
    topicStatus: '已索引 / 当前文章',
    nominal: '所有系统正常 / 2024—∞',
    stateOnline: '态矢量在线'
  },
  en: {
    metaDescription: 'greenthree blog — notes on physics, elegant algorithms, and the code that lets ideas move.',
    nav: { quantum: 'QUANTUM', notebook: 'NOTEBOOK', topics: 'TOPICS', resources: 'RESOURCES' },
    stateVector: 'STATE VECTOR / BLOCH SPHERE',
    interactive: 'INTERACTIVE',
    blochLabel: 'Interactive Bloch sphere. Use pointer or arrow keys to rotate the state vector.',
    physicsBlog: 'PHYSICS STUDENT BLOG / 001',
    hero: { line1: 'Quantum', accent: 'frontiers', joiner: '&', line3: 'algorithmic', line4: 'odysseys' },
    heroDescription: 'Notes from the overlap of rigorous physics, elegant algorithms, and the code that lets ideas move.',
    explore: 'EXPLORE THE NOTEBOOK',
    archive: 'NOTEBOOK ARCHIVE',
    articleUnit: 'ARTICLES',
    emptyArchive: 'No field notes indexed yet. Add a Markdown file to src/content/.',
    archiveInstruction: 'DROP A .MD FILE / REBUILD / PUBLISH',
    hashRoutes: 'HASH ROUTES ENABLED',
    wave: 'WAVE FUNCTION EVOLUTION',
    waveDescription: 'Visualizing wave-packet interference, probability amplitudes, and phase evolution across a discrete lattice.',
    waveLabel: 'Probability amplitude waveform',
    amplitudeLabel: 'probability amplitude',
    topics: 'TRENDING TOPICS',
    footer: 'FOOTER',
    social: 'SOCIAL',
    about: 'Site and lab journal by greenthree. Built from first principles.',
    contact: 'Contact',
    renderCore: 'RENDER CORE',
    representation: 'REPRESENTATION',
    renderTelemetry: 'Render telemetry',
    openTelemetry: 'Expand performance telemetry',
    closeTelemetry: 'Collapse performance telemetry',
    state: 'STATE',
    closeArticle: 'Close article',
    closeTopic: 'Close topic',
    endNote: 'END OF NOTE',
    returnArchive: 'RETURN TO ARCHIVE',
    loadingArticle: 'Loading article',
    copyCode: 'COPY',
    copied: 'COPIED',
    copyFailed: 'COPY FAILED',
    errorTitle: 'RENDER STATE ANOMALY',
    errorDescription: 'A rendering error occurred. Reset the view and try again.',
    reset: 'RESET STATE',
    views: 'CLICKS',
    viewsLoading: 'Loading article clicks',
    viewsUnavailable: 'Article clicks unavailable',
    openMenu: 'Open navigation',
    closeMenu: 'Close navigation',
    languageControl: 'Switch site language',
    query: 'QUERY',
    topicQueued: 'This topic comes from the live article index. Open a field note to inspect the related experiments, code, and derivations.',
    topicStatus: 'INDEXED / LIVE ARTICLES',
    nominal: 'ALL SYSTEMS NOMINAL / 2024—∞',
    stateOnline: 'STATE VECTOR ONLINE'
  }
}

export const ATLAS_COPY = {
  zh: {
    articles: {
      eyebrow: 'NOTEBOOK INDEX',
      title: '全部文章',
      description: '按时间倒序排列的全部场记、实验记录与工程笔记。',
      search: '搜索标题、摘要、分类或标签',
      count: '篇文章',
      empty: '没有匹配的文章。'
    },
    topics: {
      eyebrow: 'KNOWLEDGE MANIFOLD',
      title: '主题图谱',
      description: '从当前文章的分类与标签生成主题索引，并在每个主题下聚合相关文章。',
      search: '搜索主题或文章',
      count: '个主题',
      articles: '篇相关文章',
      empty: '没有匹配的主题。'
    },
    resources: {
      eyebrow: 'RESOURCE ATLAS',
      title: '资源导航',
      description: '连接文章、主题与项目入口的精选知识节点。',
      search: '搜索资源名称、描述或域名',
      count: '个资源',
      categories: '个分类',
      empty: '没有匹配的资源。',
      open: '打开资源'
    },
    back: '返回首页',
    result: '当前结果',
    clear: '清除搜索'
  },
  en: {
    articles: {
      eyebrow: 'NOTEBOOK INDEX',
      title: 'All Articles',
      description: 'Every field note, experiment log, and engineering journal ordered by date.',
      search: 'Search titles, summaries, categories, or tags',
      count: 'ARTICLES',
      empty: 'No matching articles.'
    },
    topics: {
      eyebrow: 'KNOWLEDGE MANIFOLD',
      title: 'Topic Atlas',
      description: 'A live index generated from article categories and tags, with related notes grouped under each topic.',
      search: 'Search topics or articles',
      count: 'TOPICS',
      articles: 'RELATED ARTICLES',
      empty: 'No matching topics.'
    },
    resources: {
      eyebrow: 'RESOURCE ATLAS',
      title: 'Resource Atlas',
      description: 'Curated knowledge nodes connecting the notebook, topics, and project work.',
      search: 'Search resource names, descriptions, or domains',
      count: 'RESOURCES',
      categories: 'CATEGORIES',
      empty: 'No matching resources.',
      open: 'Open resource'
    },
    back: 'Back home',
    result: 'CURRENT RESULTS',
    clear: 'Clear search'
  }
}
